### ISSUE TITLE
Broken linting configuration

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [lfit/github2gerrit#8]
The .pre-commit-config.yaml file has syntax errors with the prettier configuration:
https://github.com/lfit/github2gerrit/pull/3

The error is due to this stanza:
```
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 672abe14d309fc28817d45b6be25ea976a92222a # frozen: v3.0.2
    hooks:
      - id: prettier
        stages: [commit]
```

This needs to be replaced:
```
        stages: [commit]
```
...with this:
```
        stages: [pre-commit]
```
